export const CARDS = [
  { id: 1, name: 'spades_ace', img: '../img/cards/spades_ace.png', back: '../img/cards/back.png' },
  { id: 2, name: 'hearts_ace', img: '../img/cards/hearts_ace.png', back: '../img/cards/back.png' },
  {
    id: 3,
    name: 'diamonds_ace',
    img: '../img/cards/diamonds_ace.png',
    back: '../img/cards/back.png',
  },
  { id: 4, name: 'clubs_ace', img: '../img/cards/clubs_ace.png', back: '../img/cards/back.png' },
  {
    id: 5,
    name: 'spades_king',
    img: '../img/cards/spades_king.png',
    back: '../img/cards/back.png',
  },
  { id: 6, name: 'hearts_king', img: '../img/cards/hearts_kin.png', back: '../img/cards/back.png' },
  {
    id: 7,
    name: 'diamonds_king',
    img: '../img/cards/diamonds_king.png',
    back: '../img/cards/back.png',
  },
  { id: 8, name: 'clubs_king', img: '../img/cards/clubs_king.png', back: '../img/cards/back.png' },
  {
    id: 9,
    name: 'spades_queen',
    img: '../img/cards/spades_queen.png',
    back: '../img/cards/back.png',
  },
  {
    id: 10,
    name: 'hearts_queen',
    img: '../img/cards/hearts_queen.png',
    back: '../img/cards/back.png',
  },
  {
    id: 11,
    name: 'diamonds_queen',
    img: '../img/cards/diamonds_queen.png',
    back: '../img/cards/back.png',
  },
  {
    id: 12,
    name: 'clubs_queen',
    img: '../img/cards/clubs_queen.png',
    back: '../img/cards/back.png',
  },
  {
    id: 13,
    name: 'spades_jack',
    img: '../img/cards/spades_jack.png',
    back: '../img/cards/back.png',
  },
  {
    id: 14,
    name: 'hearts_jack',
    img: '../img/cards/hearts_jack.png',
    back: '../img/cards/back.png',
  },
  {
    id: 15,
    name: 'diamonds_jack',
    img: '../img/cards/diamonds_jack.png',
    back: '../img/cards/back.png',
  },
  { id: 16, name: 'clubs_jack', img: '../img/cards/clubs_jack.png', back: '../img/cards/back.png' },
  { id: 17, name: 'spades_10', img: '../img/cards/spades_10.png', back: '../img/cards/back.png' },
  { id: 18, name: 'hearts_10', img: '../img/cards/hearts_10.png', back: '../img/cards/back.png' },
  {
    id: 19,
    name: 'diamonds_10',
    img: '../img/cards/diamonds_10.png',
    back: '../img/cards/back.png',
  },
  { id: 20, name: 'clubs_10', img: '../img/cards/clubs_10.png', back: '../img/cards/back.png' },
  { id: 21, name: 'spades_9', img: '../img/cards/spades_9.png', back: '../img/cards/back.png' },
  { id: 22, name: 'hearts_9', img: '../img/cards/hearts_9.png', back: '../img/cards/back.png' },
  { id: 23, name: 'diamonds_9', img: '../img/cards/diamonds_9.png', back: '../img/cards/back.png' },
  { id: 24, name: 'clubs_9', img: '../img/cards/clubs_9.png', back: '../img/cards/back.png' },
  { id: 25, name: 'spades_8', img: '../img/cards/spades_8.png', back: '../img/cards/back.png' },
  { id: 26, name: 'hearts_8', img: '../img/cards/hearts_8.png', back: '../img/cards/back.png' },
  { id: 27, name: 'diamonds_8', img: '../img/cards/diamonds_8.png', back: '../img/cards/back.png' },
  { id: 28, name: 'clubs_8', img: '../img/cards/clubs_8.png', back: '../img/cards/back.png' },
  { id: 29, name: 'spades_7', img: '../img/cards/spades_7.png', back: '../img/cards/back.png' },
  { id: 30, name: 'hearts_7', img: '../img/cards/hearts_7.png', back: '../img/cards/back.png' },
  { id: 31, name: 'diamonds_7', img: '../img/cards/diamonds_7.png', back: '../img/cards/back.png' },
  { id: 32, name: 'clubs_7', img: '../img/cards/clubs_7.png', back: '../img/cards/back.png' },
  { id: 33, name: 'spades_6', img: '../img/cards/spades_6.png', back: '../img/cards/back.png' },
  { id: 34, name: 'hearts_6', img: '../img/cards/hearts_6.png', back: '../img/cards/back.png' },
  { id: 35, name: 'diamonds_6', img: '../img/cards/diamonds_6.png', back: '../img/cards/back.png' },
  { id: 36, name: 'clubs_6', img: '../img/cards/clubs_6.png', back: '../img/cards/back.png' },
];
